### ISSUE TITLE
Cloudlet App problem

### ISSUE THREAD

**Issue by crazysainath3** [cmusatyalab/elijah-cloudlet#10]
![app](https://f.cloud.github.com/assets/5165304/2008087/d6b39a04-8742-11e3-891c-77d07050a6d8.png)
Well as you can see as I open the application it shows me the ip mentioned in it. Why is it showing that ip? 
Well i tried to connect through upnp but it is not working. Everytime i get this ip only.

**Comment by anilce** [comment]
backend server app running on 9093 port
During Synthesis using mobile application "Cloudlet":
after successfully  transfer of overlay(vm successfully started), i am getting error "Error in connecting to ip_address:9093"
![screenshot_2015-02-24-07-47-31](https://cloud.githubusercontent.com/assets/10665333/6343956/60f30984-bc17-11e4-9c94-9a8ec7b71804.png)


please help me to solve this.

**Comment by krha** [comment]
@anilce,

Let's check a few things.
1. Does this IP matches with your cloudlet's IP address?
2. Is the cloudlet running application's VM? You can check it using either
  > $ virsh -c qemu:///session list
 or
  > $ ps aux | grep cloudlet_qemu-system-x86_64

3. If 2 is true, is the VM configured to receive data at 9093 port? You can check it using
  > $ netstat -an | grep 9093
  If the port forwarding is not configured, then please check [this part](https://github.com/cmusatyalab/elijah-provisioning/#how-to-create-vm-overlay) of readme. In short, you should set up TCP port forward of your VM. For example,

> $ cloudlet overlay /path/to/base_disk.img -- -redir tcp:2222::22 -redir tcp:8080::80

  You can do this in run-time, but requires code modification on synthesis-server. So it's easier to create VM overlay again. Thanks.

--
Kiryong

**Comment by anilce** [comment]
Hello sir,

Is their any other tool provides cloudlet(data in box) for speedup data access.

**Comment by krha** [comment]
@anilce 

Can you please give me a bit more detail? I don't get 'speedup data access' part. Thanks.

**Comment by anilce** [comment]
Sorry for last blog.

Work done by me:

I have created Amazon EC2 and S3. I have a dataset which I want to access from mobile device. I have a Ubuntu based virtual machine which I want to use as a cloudlet.

Want to do:

1. Actually I want to know is there any possible way or tool that provides cloudlet as a data center. I want cloudlet as a data storage in vicinity where I can store cached data and can access the required data from cloudlet instead of amazon cloud using smartphone. By doing this i can get better response time and reduce the network latency.
2. How can I store the requested data to my cloudlet which I got during first request from my amazon Cloud?
 
Possible solution I think:
Implementing "Caching DNS server" proximate to device. I can say this (Caching DNS serve) as cloudlet?

**Comment by krha** [comment]
@anilce 

It's glad to see that you are working on a similar problem as mine. Let me tell you how I'm trying to handle that.

I set up a proxy server at cloudlet, and the proxy server will first check cloudlet's data. It means when data at S3 is accessed, it will be cached at the cloudlet. The next access to that data will be fetched from the cloudlet with much shorter latency. If you like to know details or need collaboration, please contact to my email (krha@cmu.edu). Thanks.

--
Kiryong
