### ISSUE TITLE
Customizing Base VM

### ISSUE THREAD

**Issue by skcs** [cmusatyalab/elijah-cloudlet#32]
Dear Sir,
We are trying to implement a real time face recognition system using cloudlets. We followed the steps given by you at https://github.com/cmusatyalab/elijah-openstack to install the openstack extension for cloudlets. The dashboard launches successfully and we imported the sample base VM ubuntu 12.0.4 provided. 
After Resuming the base VM, we understand that we have to install some libraries.
![resumed vm](https://cloud.githubusercontent.com/assets/11206696/6387138/3655c066-bd9f-11e4-835f-b0b7e95ab801.png)

Could you please tell us what login id and password do we use to login into the resumed VM from the console? Also, It would be really kind of you, if you could elaborate on the customizations we have to do on the resumed VM before creating the overlay.
Kindly, help us ...

**Comment by krha** [comment]
Hello @skcs 

I think your system does not sucessfully resumed Base VM because it is supposed to resume after the login session. It looks like the system failed to resume and just rebooted the VM. To check whether it is resumed successfully or not. Please check existance of cloudlet related process by

    > $ ps aux | grep cloudlet_

If you can see running process like cloudlet_qemu-system-x86_64 while you're using a resumed VM, then I can say the system successfully resumed the base VM.

By the way, id/pass for the [sample base VM](https://storage.cmusatyalab.org/cloudlet-vm/precise-baseVM.zip) is cloudlet/cloudlet

To make sure cloudlet code is working well, please try stanalone version first at [here](https://github.com/cmusatyalab/elijah-provisioning). If the standalone version work at your compute node of OpenStack, then the rest of the process related to the OpenStack installation is much easier since both share underlying library.

------------------

Next step to creat base VM after installing your stuff on the Base VM is just clicking 'create VM overlay' button as shown in the 'Instance' table of the image.
![Creating VM overlay](https://github.com/cmusatyalab/elijah-openstack/blob/icehouse/doc/screenshot/creating_vm_overlay.png?raw=true)

Then the VM overlay that contains your customized part will be created and will be downloadable at 'Images' table.

**Comment by skcs** [comment]
Sir,
I am able to login into the resumed VM using the id and password now.
![resumed vm console](https://cloud.githubusercontent.com/assets/11206696/6429611/cde6036e-bff7-11e4-9dc9-3f35a04ac5cf.png)
When I check for the existance of cloudlet while using the resumed VM, I can see a "cloudlet" process but not "cloudlet_qemu-system-x86_64".
![checking existance of resumed vm](https://cloud.githubusercontent.com/assets/11206696/6429613/1015470e-bff8-11e4-8e73-ce375e2747d5.png)
Are there any mistakes in my installations?

**Comment by krha** [comment]
Hello @skcs 

Since cloudlet-related processes are not running, I think the cloudlet code does not successfully run.

Do you still have a problem creating VM overlay? If you do, please try stanalone version first at https://github.com/cmusatyalab/elijah-provisioning. If the standalone version work at your compute node of OpenStack, then the rest of the process related to the OpenStack installation is much easier since both share underlying library.

--
Kiryong

**Comment by skcs** [comment]
Sir,
Before creating the VM Overlay, I understand that I have to load some libraries into the resumed VM. Can you please explain what files have to be moved to the resumed VM from my Face Detection Project in Eclipse?
