### ISSUE TITLE
Face Recognition Server

### ISSUE THREAD

**Issue by SainathK333** [cmusatyalab/elijah-cloudlet#7]
Hii,
     In Vm based Cloudlet paper  it is mentioned that Face recognition server runs on windows. Is it necessarily windows or can it be run on linux also?
Well i have another doubt regarding the steps
1.First i send an overlay through the cloudlet app and i receive it on the other end and then i perform Dynamic Vm Synthesis.After this should i run a new server?

**Comment by anilce** [comment]
Thanks for your kind response.

1. If I want to work on face recognition application and want to cache data on cloudlet then, is cloudlet provide any kind of caching scheme. If not then how can I do it.

2. If I want to make decision that request only handled if cloudlet connection is good.  Then what to do.

**Comment by krha** [comment]
@anilce 

    >If I want to work on face recognition application and want to cache data on cloudlet then, is cloudlet provide any kind of caching scheme. If not then how can I do it.


--> The current version does not support any caching mechanism. I'm actually working on this, but will take some time to be updated to the repo. I have several thoughts on this caching mechanism, but I'm not sure I can share it now at the public place, since we're in the middle of developing idea. 



    > If I want to make decision that request only handled if cloudlet connection is good. Then what to do.


--> I haven't though about it, but just an impromptu idea. If you know about your application, then you might have expected computing time of your application. That means, you can roughly estimate time consumed on the network by measuring a response time of your application. (network_time_to_cloudlet = total_respone_time -  computing_time). From this network time, you can tell whether cloudlet connection is good or not. Thanks.

--
Kiryong
